number=[10,29,34,78]
print(number)
total=sum(number)
print(total)
number.append(67)
print(number)
number.insert(1,8)
print(number)
number.remove(34)
print(number)
print(len(number))
print(max(number))
print(min(number))
number.sort()
print(number)
for i in number:
    print(i)
name="prah"
print(name)
print(name.upper())
print(name.lower())
print(len(number))
print(number[::-1])
number=(10,20,30,49)
print(number)
print(number[1])
print(len(number))
print(number[::-1])
print(number.count(20))
print(number.index(20))
print(30 in number)
print(number[1:4])
number=[10,56,89]
result=tuple(number)
print(result)
print(max(number))

