fruit=('apple','mango','orng')
print(fruit)
my_tuple=(1,2,7)
print(my_tuple)
print(type(my_tuple))
my_tuble=(1,"geet",True,3.15)
print(my_tuble)
truple=1,2,3
print(my_tuple)
print(type(my_tuple))
tuple2=tuple((1,5,6))
print(type(tuple2))
print(tuple2)
list=["sg","pv"]
new_tuple=tuple(list)
print(new_tuple)
a=("a", )
print(a)
fruits=('apple','mango','orange')
print(fruits[1])
print(fruits[2])
print(fruits[0])
print(fruits[-1])
tuple1=[1,2]
tuple2=['a','d','c']
tuple3=tuple1+tuple2
print(tuple3)
tuple3=(1,3,6)*4
print(tuple3)
tuple4=(1,3,6)
print(10 in tuple4)
fruits=('apple','mango','cherry')
for i in fruits:
    print(i)
    i=0
    while i<len(fruits):
        print(fruits[i])
        i+=1
    color=('blue','red','orage','green')
    print(color.count('green'))
    print(color.index('blue'))
    numbers=(2,3,4,1)
    print(len(numbers))
    print(sum(numbers))
    print(min(numbers))
    print(max(numbers))
    a=sorted(numbers)
    num_sorted=tuple(a)
    print(num_sorted)
a="geet"
b=23
c="teacger"
tuple_pack=a,b,c
print(tuple_pack)
name,age,profession=tuple_pack
print(name)
print(age)
print(profession)
tuple_numbers=(10,20,30)

