fruit=('apple','mango','orng')
print(fruit)
my_tuple=(1,2,7)
print(my_tuple)
print(type(my_tuple))
my_tuble=(1,"geet",True,3.15)
print(my_tuble)
truple=1,2,3
print(my_tuple)
print(type(my_tuple))
tuple2=tuple((1,5,6))
print(type(tuple2))
print(tuple2)
list=["sg","pv"]
new_tuple=tuple(list)
print(new_tuple)
a=("a", )
print(a)
fruits=('apple','mango','orange')
print(fruits[1])
print(fruits[2])
print(fruits[0])
print(fruits[-1])
tuple1=[1,2]
tuple2=['a','d','c']
tuple3=tuple1+tuple2
print(tuple3)